### ISSUE TITLE
On-Prem SSL configuration

### ISSUE THREAD

**Issue by mitchell-johnson** [microsoft/vsts-agent-docker#124]
Hi all 

I am trying to connect to my on-prem install of tfs 2018 with this agent and am having issues with the SSL configuration

using image `microsoft/vsts-agent:ubuntu-16.04-tfs-2018-u2`

The url I am trying to connect to is https://myorg.com
and when I run `curl https://myorg.com` it succeeds but when I run start.sh I receive in the logs the following when I try to run start.sh
`GET request to https://myorg.com/tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates`

Using the flag `--sslskipcertvalidation` seems to have no effect

**Comment by dakale** [comment]
Where did you pass `--sslskipcertvalidation`? The images start the agent like so: https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/tfs/start.sh#L61

I think adding `${VSTS_SSLSKIPCERTVALIDATION:+--sslskipcertvalidation} \` to the launch options would work: 

```bash
./bin/Agent.Listener configure --unattended \
  ${VSTS_SSLSKIPCERTVALIDATION:+--sslskipcertvalidation} \
  --agent "${VSTS_AGENT:-$(hostname)}" \
  --url "$TFS_URL" \
  --auth PAT \
  --token $(cat "$VSTS_TOKEN_FILE") \
  --pool "${VSTS_POOL:-Default}" \
  --work "${VSTS_WORK:-_work}" \
  --replace & wait $!
```

then you would run the container with -e VSTS_SSLSKIPCERTVALIDATION=true

I dont have an environment set up at the moment to test it.

If you are willing to rebuild the image you are using with this change to verify, that would be great (let me know if you need help), otherwise I can but it will take longer to get everything prepared.

**Comment by mitchell-johnson** [comment]
Thanks @dakale Ill take a look now and report back

**Comment by mitchell-johnson** [comment]
That change seemed to have no effect. Logs are the same and I have verified that start.sh is correct 
`
./bin/Agent.Listener configure --unattended \
  ${VSTS_SSLSKIPCERTVALIDATION:+--sslskipcertvalidation} \
  --agent "${VSTS_AGENT:-$(hostname)}" \
  --url "$TFS_URL" \
  --auth PAT \
  --token $(cat "$VSTS_TOKEN_FILE") \
  --pool "${VSTS_POOL:-Default}" \
  --work "${VSTS_WORK:-_work}" \
  --replace & wait $!`

**Comment by dakale** [comment]
Hm, thats too bad. Just to be sure, did you run the container with `docker run -e VSTS_SSLSKIPCERTVALIDATION=true`? I want to make sure that flag would actually be set. 

If you did pass that into the environment, would you mind trying changing the start.sh to just hardcode `--sslskipcertvalidation` instead of having it inside the parameter substitution? If you did already try that, let me know and ill investigate further

**Comment by mitchell-johnson** [comment]
@dakale I must have missed something the first time. I am still having SSL issues but the error is slightly different now. In the logs I see the flag has been passed 
```[2018-08-07 19:32:43Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'True'
[2018-08-07 19:32:43Z INFO ConfigurationManager] Reset agent cert setting base on commandline args.
[2018-08-07 19:32:43Z INFO AgentCertificateManager] Setup agent certificate setting base on configuration inputs.
[2018-08-07 19:32:43Z INFO AgentCertificateManager] Ignore SSL server certificate validation error```

and the error I am seeing is 
```[2018-08-07 19:32:43Z INFO CommandSettings] Remove url from Arg dictionary.
[2018-08-07 19:32:43Z INFO ConfigurationManager] GetCredentialProvider
[2018-08-07 19:32:43Z INFO CommandSettings] Arg 'auth': 'PAT'
[2018-08-07 19:32:43Z INFO CommandSettings] Remove auth from Arg dictionary.
[2018-08-07 19:32:43Z INFO ConfigurationManager] Creating credential for auth: PAT
[2018-08-07 19:32:43Z INFO CredentialManager] GetCredentialProvider
[2018-08-07 19:32:43Z INFO CredentialManager] Creating type PAT
[2018-08-07 19:32:43Z INFO CredentialManager] Creating credential type: PAT
[2018-08-07 19:32:43Z INFO PersonalAccessToken] EnsureCredential
[2018-08-07 19:32:43Z INFO CommandSettings] Arg 'token': '***'
[2018-08-07 19:32:43Z INFO CommandSettings] Remove token from Arg dictionary.
[2018-08-07 19:32:43Z INFO PersonalAccessToken] GetVssCredentials
[2018-08-07 19:32:43Z INFO PersonalAccessToken] token retrieved: 38 chars
[2018-08-07 19:32:43Z INFO ConfigurationManager] cred retrieved
[2018-08-07 19:32:43Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-08-07 19:33:59Z ERR  VisualStudioServices] GET request to https://myorg.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()```

**Comment by dakale** [comment]
Im still investigating but I found a similar issue: https://github.com/Microsoft/vsts-agent/issues/1440,
although this relates to installing your certs rather than ignoring them altogether. 

@TingluoHuang Do you know off the top of your head why there would be SSL errors in the agent even when attempting to ignore with `--sslskipcertvalidation` ?

**Comment by TingluoHuang** [comment]
@mitchell-johnson 
did you pass the right PAT?
```
[2018-08-07 19:32:43Z INFO CredentialManager] Creating type PAT
[2018-08-07 19:32:43Z INFO CredentialManager] Creating credential type: PAT
[2018-08-07 19:32:43Z INFO PersonalAccessToken] EnsureCredential
[2018-08-07 19:32:43Z INFO CommandSettings] Arg 'token': '***'
[2018-08-07 19:32:43Z INFO CommandSettings] Remove token from Arg dictionary.
[2018-08-07 19:32:43Z INFO PersonalAccessToken] GetVssCredentials
[2018-08-07 19:32:43Z INFO PersonalAccessToken] token retrieved: 38 chars
```

PAT suppose to be 52 chars, why you get 38 chars?

**Comment by mitchell-johnson** [comment]
Thanks for the reply @TingluoHuang I should have been but Ill double check my config on Monday
